# Étape 1 — Build Vue.js
FROM node:20-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

# Étape 2 — Servir avec nginx
FROM nginx:alpine
COPY --from=builder /app/dist    /usr/share/nginx/html
COPY infra/docker/nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
